FROM python:3.8-slim

WORKDIR /app

ADD . /app

RUN apt-get update && apt-get install -y libgomp1

RUN pip install -r requirements.txt

EXPOSE 8745

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8745"]
